import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image';
import Images from '../componets/Images';
import styles from '../../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id={styles.main} className={styles.container}>
        {/** HOME */}
        <section id={styles.home} className={styles.container}>
          <Image src={Images.Profile} alt="profile" className={styles.img} width={80} height={80}/>
          <h2>rsanttos</h2>
          <a href="https://www.instagram.com/holy_programmer/" target="_blank" rel="noopener noreferrer">@holy_programmer</a>

          {/** SOCIAL CONTAINER */}
          <div className={`${styles.container} ${styles.social}`}>
            <a title="instagram" href="https://www.instagram.com/rsanttos89/" target="_blank" rel="noopener noreferrer">
              <Image src={Images.Instagram} alt="profile" width={80} height={80}/>
            </a>

            <a title="github" href="https://github.com/r-santtos" target="_blank" rel="noopener noreferrer">
              <Image src={Images.GitHub} alt="profile" width={80} height={80}/>
            </a>

            <a title="linkedin" href="https://www.linkedin.com/in/rsanttos89/" target="_blank" rel="noopener noreferrer">
              <Image src={Images.Linkedin} alt="profile" width={80} height={80}/>
            </a>
          </div>
        </section>

        {/** TIMES CONTAINER */}
        <section id={styles.times} className={styles.container}>
          {/** TIME BOX */}
          <div className={`${styles.container}, ${styles.timeBox}`}>
            {/** TIME BAR */}
            <div className={`${styles.container} ${styles.timeBar}`}>
              <p>Dias como programador</p>
              <span className={`${styles.container} ${styles.lineOne}`}>
                <span id={styles.lineTwos} className={`${styles.container} ${styles.lineTwo}`}></span>
              </span>
              <p id={styles.dayss}>000</p>
            </div>
          </div>
        </section>

        {/** TIMES CONTAINER */}
        <h3>Final do ano &#10097;&#10097;</h3>
        <section id={styles.times} className={styles.container}>
          {/** TIME BOX */}
          <div className={`${styles.container}, ${styles.timeBox}`}>
            {/** BOX RIGHT */}
            <div className={`${styles.container} ${styles.right}`}>
              <div className={`${styles.container} ${styles.boxRight}`}>
                {/** <!-- DAYS --> */}
                <div className={`${styles.container} ${styles.number}`}>
                  <p id={styles.days}>000</p>
                  <p>dias</p>
                </div>

                <span className={`${styles.container} ${styles.points}`}>:</span>

                {/** HOURS */}
                <div className={`${styles.container} ${styles.number}`}>
                  <p id={styles.hours}>00</p>
                  <p>horas</p>
                </div>

                <span className={`${styles.container} ${styles.points} ${styles.last}`}>:</span>

                {/** MINUTES */}
                <div className={`${styles.container} ${styles.number}`}>
                  <p id={styles.minutes}>00</p>
                  <p>minutos</p>
                </div>

                <span className={`${styles.container} ${styles.points}`}>:</span>

                {/** SECONDS */}
                <div className={`${styles.container} ${styles.number}`}>
                  <p id={styles.seconds}>00</p>
                  <p>segundos</p>
                </div>
              </div>

              {/** TIME BAR */}
              <div className={`${styles.container} ${styles.timeBar}`}>
                <p>Regressiva</p>
                <span className={`${styles.container} ${styles.lineOne}`}>
                  <span id={styles.lineTwo} className={`${styles.container} ${styles.lineTwo}`}></span>
                </span>
                <p>2022</p>
              </div>
            </div>
          </div>
        </section>
      </main>

      <footer id={styles.footer} className={styles.container}>
        <p>ricardo santtos&copy;2022</p>
      </footer>
    </div>
  )
}

export default Home
